# Generated by Django 2.2 on 2019-05-30 19:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hr.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('complete_name', models.CharField(max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('kra_pin', models.CharField(blank=True, max_length=64, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=64, null=True)),
                ('nhif', models.CharField(blank=True, max_length=64, null=True)),
                ('nssf', models.CharField(blank=True, max_length=64, null=True)),
                ('job_title', models.CharField(blank=True, max_length=128, null=True)),
                ('identification_id', models.CharField(blank=True, max_length=64, null=True)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('N', 'Dont say'), ('O', 'Other')], default='F', max_length=2)),
                ('active', models.BooleanField(default=True)),
                ('marital', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('cohabitant', 'Legal Cohabitant'), ('widower', 'Widower'), ('divorced', 'Divorced')], default='single', max_length=64)),
                ('spouse_complete_name', models.CharField(blank=True, max_length=128, null=True)),
                ('spouse_birthdate', models.DateField(blank=True, null=True)),
                ('number_of_children', models.IntegerField(blank=True, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=128, null=True)),
                ('country_of_birth', models.CharField(blank=True, max_length=128, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('permit_no', models.CharField(blank=True, max_length=64, null=True)),
                ('visa_no', models.CharField(blank=True, max_length=64, null=True)),
                ('visa_expire', models.DateField(blank=True, null=True)),
                ('education_level', models.CharField(choices=[('primary', 'Primary School'), ('secondary', 'Secondary School')], default='secondary', max_length=64)),
                ('study_field', models.CharField(blank=True, max_length=64, null=True)),
                ('study_school', models.CharField(blank=True, max_length=64, null=True)),
                ('work_phone', models.CharField(blank=True, max_length=64)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('emergency_contact', models.CharField(blank=True, max_length=64)),
                ('emergency_phone', models.CharField(blank=True, max_length=64, null=True)),
                ('google_drive_link', models.CharField(blank=True, max_length=64, null=True)),
                ('image', models.ImageField(default='https://www.gravatar.com/avatar/', upload_to=hr.models.user_directory_path)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.Department')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Next_of_keen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
                ('relationship', models.CharField(blank=True, max_length=64)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('N', 'Dont say'), ('O', 'Other')], default='F', max_length=2)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=64)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=64)),
                ('days', models.DecimalField(decimal_places=1, max_digits=4)),
                ('start_date', models.DateField()),
                ('end_time', models.DateField()),
                ('reason', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_l', to='hr.Employee')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to='hr.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='manager_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_department', to='hr.Employee'),
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='hr.Department'),
        ),
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('N', "Don't say"), ('O', 'Other')], default='F', max_length=2)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=64)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField()),
                ('check_out_time', models.DateTimeField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Employee')),
            ],
        ),
    ]
