# Generated by Django 2.2 on 2019-05-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='check_in_time',
            new_name='check_in',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_out_time',
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
